spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: update
spring.sql.init.mode: always
spring.jpa.defer-datasource-initialization: true

camunda.bpm.admin-user:
  id: demo
  password: demo
